name: Lint Powershell Scripts

on:
  pull_request:

jobs:
  analyze-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Powershell
      shell: bash
      run: |
        sudo apt update -y && sudo apt install powershell -y 


    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -SkipPublisherCheck

    - name: Analyze PowerShell scripts and post results
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $results = @()
        $scripts = Get-ChildItem -Path . -Filter *.ps1 -Recurse
        foreach ($script in $scripts) {
          Write-Host "Analyzing $($script.FullName)"
          $analysisResult = Invoke-ScriptAnalyzer -Path $script.FullName -EnableExit
          $results += $analysisResult
        }
        $url = "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$GITHUB_ISSUE_NUMBER/comments"
        Invoke-RestMethod -Uri $url -Headers @{Authorization="Bearer $env:GITHUB_TOKEN"} -Method POST -Body @{body=$results} -ContentType "application/json"
