name: Lint Powershell Scripts

on:
  pull_request:

jobs:
  analyze-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Powershell
      shell: bash
      run: |
        sudo apt update -y && sudo apt install powershell -y 


    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -SkipPublisherCheck

    - name: Analyze PowerShell scripts and post results
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $results = @()
        $scripts = Get-ChildItem -Path . -Filter *.ps1 -Recurse
        foreach ($script in $scripts) {
          Write-Host "Analyzing $($script.FullName)"
          $analysisResult = Invoke-ScriptAnalyzer -Path $script.FullName -EnableExit
          $results += $analysisResult
        }
        $uri = "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
        $token = $env:GITHUB_TOKEN
        $headers = @{
          "Content-Type" = "application/json"
          "Authorization" = "Bearer $token"
        }
        # Define the comment body
        $body = @{
          "body" = $results
        } | ConvertTo-Json
        # Invoke the REST API
        Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body
